name: Clay for Ubuntu

on:
  push:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, ':construction:') || contains(github.event.head_commit.message, ':ubuntu:')

    steps:
    - uses: actions/checkout@v2

    - name: Prepare
      run: |
        sudo apt-get install
        sudo apt-get -qq update
        sudo apt-get -y install gcc clang
        sudo apt-get -y install xz-utils python3 libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev libxext-dev libunwind-dev glibc-source
      
    - name: Make
      run: |
        chmod +x init-repo.sh
        ./init-repo.sh
        